### ISSUE TITLE
In the new re-factor "scroll build" has to be used in each specific directory.

### ISSUE THREAD

**Issue by fractalqualia** [breck7/hawaii.pub#1]
The early folder structure had all the files sitting in one folder and 'scroll build' would work fine. However, now for the stories folder you have to go inside it and then do 'scroll build' which is an added step. Is there some way around it?  Sometimes I think it's my server causing issues and not rendering fine.

**Comment by breck7** [comment]
Sorry about that! To recursively build scrolls run this `scroll list | scroll build`. This will pipe the list from `scroll list` and build each item.

An example:
https://github.com/breck7/hawaii.pub/blob/415936acfea1bd59a2db7966d4d4f8dd3e2c0629/.github/workflows/buildAndDeployScroll.yaml#L16
